version: 2
models:
  - name: hub_customer
    config: {schema: core}
  - name: hub_transaction
    config: {schema: core}
  - name: hub_product
    config: {schema: core}
  - name: hub_store
    config: {schema: core}
  - name: hub_card
    config: {schema: core}
  - name: hub_loyalty_transaction
    config: {schema: core}
  - name: hub_employee
    config: {schema: core}
  - name: link_transaction
    config: {schema: core}
  - name: link_sale
    config: {schema: core}
  - name: link_customer_card
    config: {schema: core}
  - name: link_loyalty_transaction
    config: {schema: core}
  - name: sat_transaction_details
    config: {schema: core}
  - name: sat_sale
    config: {schema: core}
  - name: sat_client
    config: {schema: core}
  - name: sat_card
    config: {schema: core}
  - name: sat_loyalty_txn
    config: {schema: core}
  - name: sat_employee
    config: {schema: core}
  - name: sat_product_static
    config: {schema: core}
  - name: sat_store
    config: {schema: core}
