horizon:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER', 'horizon') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'horizon') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'horizon') }}"
      schema: marts
      threads: 4
