version: 2
models:
  - name: stg_sales
    config: {schema: staging}
  - name: stg_clients
    config: {schema: staging}
  - name: stg_cards
    config: {schema: staging}
  - name: stg_loyalty_transactions
    config: {schema: staging}
  - name: stg_hr
    config: {schema: staging}
  - name: stg_products
    config: {schema: staging}
  - name: stg_stores
    config: {schema: staging}
